USE ECOMMERCEDB;
-- View
SELECT * FROM CUSTOMERS;
CREATE VIEW  CUSTOMER_INFO AS
SELECT NAME AS CUSTOMER_ID, NAME AS CUSTOMER_NAME, EMAIL, PHONE FROM CUSTOMERS;
SELECT * FROM CUSTOMER_INFO;

-- VIEW WITH JOINS
CREATE VIEW CUSTOMER_ORDERS AS 
SELECT C.NAME AS CUSTOMER_NAME, C.CUSTOMER_ID, O.ORDER_ID, O.ORDER_DATE, O.TOTAL_AMOUNT 
FROM CUSTOMERS C JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID;
SELECT * FROM CUSTOMER_ORDERS;

-- FULL ORDER DETAILS
CREATE VIEW FULLORDERDETAILS AS
SELECT C.CUSTOMER_ID,C.NAME AS CUSTOMER_NAME, O.ORDER_ID, P.NAME, OI.QUANTITY, P.PRICE,
(OI.QUANTITY*P.PRICE) AS TOTAL_PRICE,O.ORDER_DATE FROM ORDERS o
JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
JOIN ORDER_ITEMS OI ON O.ORDER_ID = OI.ORDER_ID
JOIN PRODUCTS P ON OI.PRODUCT_ID = P.PRODUCT_ID; 

SELECT * FROM FULLORDERDETAILS;
SELECT * FROM FULLORDERDETAILS WHERE CUSTOMER_NAME = "RAM";

-- VIEW WITH FILTERING 
CREATE VIEW HIGHRATEORDERS AS
SELECT C.CUSTOMER_ID, C.NAME AS CUSTOMER_NAME, O.ORDER_ID, O.ORDER_DATE, O.TOTAL_AMOUNT
FROM CUSTOMERS C 
JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
WHERE O.TOTAL_AMOUNT > 200;

SELECT * FROM HIGHRATEORDERS ;

SHOW CREATE VIEW CUSTOMER_ORDERS;